title: HuBo awesome title
email: 969559629@qq.com
description: >- # this means to ignore newlines until "baseurl:"
    My Blog For Something.
baseurl: ""
url: ""
github_username:  jekyll

paginate: 5
paginate_path: "/_posts"
theme: minima

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
      
plugins:
  - jekyll-feed

